services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: cwm
      POSTGRES_PASSWORD: cwm_password
      POSTGRES_DB: gestao_de_usuarios
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cwm -d gestao_de_usuarios" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
